language: go

go:
  - 1.13.x

env: GO111MODULE=on

# Only clone the most recent commit.
git:
  depth: 1


#envisionned steps:
  #unit tests
  #docker image build
  #integration tests (should probably run using a specific docker-compose)

  #stop here if it is not a merge to staging or master

  #git tagging based of major / minor / fix (in PR name ?)
  #image tagging based of git tag
  #push to docker image to registry

#env:
#TRAVIS_BRANCH:
  #
  #    for push builds, or builds not triggered by a pull request, this is the name of the branch.
  #    for builds triggered by a pull request this is the name of the branch targeted by the pull request.
  #    for builds triggered by a tag, this is the same as the name of the tag (TRAVIS_TAG).

#TRAVIS_COMMIT_MESSAGE: The commit subject and body, unwrapped.
#TRAVIS_PULL_REQUEST: The pull request number if the current job is a pull request, “false” if it’s not a pull request.
