language: go

go:
  - 1.13.x

services:
  - docker

env:
#  - GO111MODULE=on    why does it creates two jobs ?
  - DOCKER_COMPOSE_VERSION=1.21.2

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
# Only clone the most recent commit.
git:
  depth: 1

script:
  - docker-compose -f docker-compose.test.yml build
  - docker-compose -f docker-compose.test.yml -p diary-tests up -d
  - docker exec -it diary-tests_diary-api_1 go test ./... -race -coverprofile=coverage.txt -covermode=atomic

jobs:
  include:
    - stage: test
      script:
        - docker-compose -f docker-compose.test.yml build
        - docker-compose -f docker-compose.test.yml -p diary-tests up -d
        - docker exec -it diary-tests_diary-api_1 go test ./... -race -coverprofile=coverage.txt -covermode=atomic
      after_success:
        - bash <(curl -s https://codecov.io/bash)
    - stage: deploy
      script:
        - echo "TO DO"
#        - sudo apt install gawk
#        - export NEXT_TAG=$(./get_next_tag.sh $TRAVIS_PULL_REQUEST_BRANCH $(git describe --abbrev=0))
#        - echo "Next version = $NEXT_TAG"
#        - docker build -t yuruh/encrypted-diary-web-app:$NEXT_TAG .
#        - docker login -u yuruh -p $DOCKER_PWD
#        - git tag -a $NEXT_TAG -m "$TRAVIS_COMMIT_MESSAGE"
#        - git push "https://$GITHUB_TOKEN@github.com/Yuruh/encrypted-diary-web-app.git --tags
#        - docker push yuruh/encrypted-diary-web-app:$NEXT_TAG