# This docker-compose file exists for development purposes. The one used in production can be found here:
# https://github.com/Yuruh/Yuruh/blob/master/docker-compose.diary.yml

version: "3.5"
services:
  diary-postgres:
    image: "postgres:12.1"
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: changeme
    volumes:
      - /data/postgresql:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: antoine.lempereur@epitech.eu
      PGADMIN_DEFAULT_PASSWORD: azerazer
    ports:
      - 1500:80
    volumes:
      - pgadmin-data:/var/lib/pgadmin
  diary-api:
    #network_mode: host
    environment:
      - DB_HOST=postgres
    build: "."
    volumes:
      - ./src:/usr/src/diary/src
    ports:
      - 8080:8080
    depends_on:
      - diary-postgres

volumes:
  pgadmin-data:
