# This docker-compose file exists for development purposes. The one used in production can be found here:
# https://github.com/Yuruh/Yuruh/blob/master/docker-compose.diary.yml

version: "3.5"
services:
  postgres:
    image: "postgres:12.1"
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${DIARY_DB_USER}
      POSTGRES_PASSWORD: ${DIARY_DB_PWD}
    volumes:
      - /data/postgresql/diary:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_USER}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PWD}
    ports:
      - 1500:80
    volumes:
      - pgadmin-data:/var/lib/pgadmin
  api:
    environment:
      - DB_HOST=postgres
    container_name: api
    build: "."
    volumes:
      - ./src:/usr/src/diary/src
      - ${PWD}/openapi.yml:/usr/src/diary/openapi.yml
    ports:
      - 8080:8080
    depends_on:
      - postgres
    env_file:
      - .env
  doc:
    container_name: doc
    image: "redocly/redoc"
    environment:
      - PAGE_TITLE=API Doc - Encrypted Diary
      - PAGE_FAVICON=https://app.diary.yuruh.fr/favicon.ico
      - SPEC_URL=http://localhost:8080/openapi.yml
    ports:
      - "8082:80"
volumes:
  pgadmin-data:
